### Probar la creación de un nuevo empleado
POST http://localhost:4000/employees
Content-Type: application/json

{
  "nombre": "Carlos",
  "apellido": "Ramírez",
  "email": "carlos.ramirez@example.com",
  "puesto": "Ingeniero de Software",
  "salario": 70000
}

### Obtener todos los empleados
GET http://localhost:4000/employees

### Obtener un empleado por ID
GET http://localhost:4000/employees/664967739585f3d5cfbe8985

### Actualizar un empleado por ID
PUT http://localhost:4000/employees/664967739585f3d5cfbe8985
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "email": "juan.perez@example.com",
  "puesto": "Desarrollador Senior",
  "salario": 60000
}

### Eliminar un empleado por ID
DELETE http://localhost:4000/employees/664967739585f3d5cfbe8985

### Crear un nuevo proyecto
POST http://localhost:4000/projects
Content-Type: application/json

{
  "nombre": "Primer  Proyecto HTML",
  "descripcion": "HTML",
  "empleado": "664a570a9585f3d5cfbe89c2"
}

### Actualizar el porcentaje de avance de un proyecto y agregar una nota
PUT http://localhost:4000/projects/664a6c1a6d0badab5269a9c0/progress
Content-Type: application/json

{
  "porcentajeAvance": 80,
  "nota": "Avance del 80% completado"
}

### Obtener todos los proyectos
GET http://localhost:4000/projects

### Obtener un proyecto por ID
GET http://localhost:4000/projects/ID_DEL_PROYECTO

### Eliminar un proyecto por ID
DELETE http://localhost:4000/projects/ID_DEL_PROYECTO

